apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  namespace: homework
  labels:
    app: web-server
spec:
  initContainers:
    - name: init
      image: busybox
      command: ["sh", "-c", "echo 'Hello World' > /init/index.html"]
      volumeMounts:
        - name: shared-volume
          mountPath: /init

  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-volume
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["rm", "/homework/index.html"]


  volumes:
    - name: shared-volume
      emptyDir: {}
    - name: nginx-conf
      configMap:
        name: nginx-config
